### PR TITLE
Upgrade `cs2-lib`

### PR DESCRIPTION
**Pull request by ianlucas**
The newer version of `cs2-lib` had a lot of refactoring and changes for stickers & patches. This PR contains the code changes for supporting it.

### CODE REVIEW

**Comment by Hyroo1** [comment]
Hello! I have question how can i integrated with cs2 server ?

**Comment by ianlucas** [comment]
> Hello! I have question how can i integrated with cs2 server ?

Not really the place to have this conversation, but look at my other repos and the [API documentation](https://github.com/ianlucas/cs2-inventory-simulator/blob/main/docs/api.md).

**Comment by Hyroo1** [comment]
also did you try any server ?

**Comment by ianlucas** [comment]
> also did you try any server ?

Please use the "Discussions" tab if you have any questions related to the app, but we assume you have some technical knowledge if you are asking questions, so don't expect an answer for stuff unrelated to the project.

**Pull request merged**
